version: '3'

services:
  mysql-db:
    container_name: mysql-db
    image: 'mysql:latest'
    environment:
      - MYSQL_USER=m1rrox
      - MYSQL_ROOT_PASSWORD=528193746
      - MYSQL_PASSWORD=528193746
    volumes:
      - ./database_data:/var/lib/mysql
      - ./src/main/resources/data/:/tmp/database
    command: mysqld --init-file="/tmp/database/itunes_db_scenarious.sql"

  spring-boot-app:
    container_name: spring-boot-app
    build: .
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/ostap_koziaryk_itunes_full
      - SPRING_DATASOURCE_USERNAME=m1rrox
      - SPRING_DATASOURCE_PASSWORD=528193746
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
        - '8082:8083'
    depends_on:
      - mysql-db

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - spring-boot-app

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"