spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ostap_koziaryk_itunes_full
    username: mirrox322
    password: 528193746
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8081
